enum Section {
    TRAINER_INFO, TEAM_ITEMS, GAME_STATE, MISC_DATA, RIVAL_INFO,
    PC_BUFFER_A, PC_BUFFER_B, PC_BUFFER_C, PC_BUFFER_D, PC_BUFFER_E, PC_BUFFER_F,
    PC_BUFFER_G, PC_BUFFER_H, PC_BUFFER_I,
}

export { Section };